# Generated by Django 4.2.25 on 2025-10-21 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='uploads/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='uploads/processed/')),
                ('filter_type', models.CharField(choices=[('gray', 'Grayscale'), ('sepia', 'Sepia'), ('poster', 'Poster'), ('blur', 'Blur'), ('edge', 'Edge Detection'), ('solar', 'Solar')], max_length=20)),
                ('s3_url', models.URLField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Processed Image',
                'verbose_name_plural': 'Processed Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
